### ISSUE TITLE
Should we "implement" `RowVecs` and `ColVecs` from KernelFunctions.jl?

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/ExactOptimalTransport.jl#14]
Once we make the `discretemeasure` function available to users, they will have to use:
```
using KernelFunctions
# rows correspond to samples
μ = discretemeasure(RowVecs(rand(7,3)), normalize!(rand(10),1))

# columns correspond to samples, each with equal probability
ν = discretemeasure(ColVecs(rand(3,12)))
```
So I think it would be nice to have `ColVecs` and `RowVecs` available inside our package.

**Comment by devmotion** [comment]
I opened an issue in KernelFunctions: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/394 I think we should be able to refactor them into a separate package quite quickly if we push it a bit :slightly_smiling_face:
