### ISSUE TITLE
Why does Wasserstein differ from scipy?

### ISSUE THREAD

**Issue by itsdfish** [JuliaOptimalTransport/ExactOptimalTransport.jl#29]
Hi,

I was wondering why the results for `wasserstein` differ from scipy. I didn't see anything different in terms of configuration.

Thanks!

**Julia**

```
using ExactOptimalTransport
wasserstein(Categorical([0, .25, .75]), Categorical([.4,.4,.2]))
# output 0.9500000000000001
```

**Python**

```
import scipy
scipy.stats.wasserstein_distance([.0,.25,.75], [.4,.4,.2])
# output 0.23333333333333334
```

**Comment by zsteve** [comment]
In the Julia code, you're computing the 1-Wass distance between two discrete measures that share a common support on [1, 2, 3] (that's how Categorical works). 
On the other hand, to my understanding from the documentation of the scipy funciton (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html) the inputs `u, v` are actually the empirical points. 
For comparison:
```

julia> wasserstein(DiscreteNonParametric([.0,.25,.75], [1/3, 1/3, 1/3]), DiscreteNonParametric([.4,.2], [2/3, 1/3]))
0.23333333333333334
```
