### ISSUE TITLE
How to cite this package

### ISSUE THREAD

**Issue by ignace-computing** [JuliaOptimalTransport/ExactOptimalTransport.jl#34]
Hello,

How can this package be cited?

Thank you,
Best wishes

**Comment by zsteve** [comment]
Hi @ignace-computing , 
@devmotion registered the the main OptimalTransport.jl package on Zenodo (https://zenodo.org/record/5920148), and in principle the ExactOptimalTransport.jl package could be viewed as an extension thereof. 

Thus, please cite as 
```
@software{stephen_zhang_2022_5920148,
  author       = {Stephen Zhang and
                  David Widmann and
                  Davi Sales Barreira},
  title        = {JuliaOptimalTransport/OptimalTransport.jl: v0.3.19},
  month        = jan,
  year         = 2022,
  publisher    = {Zenodo},
  version      = {v0.3.19},
  doi          = {10.5281/zenodo.5920148},
  url          = {https://doi.org/10.5281/zenodo.5920148}
}
```

**Comment by ignace-computing** [comment]
Thank you for your answer!

Would it make sense to add this information to 
https://github.com/JuliaOptimalTransport/OptimalTransport.jl?

**Comment by devmotion** [comment]
The README contains a badge with the DOI: https://github.com/JuliaOptimalTransport/OptimalTransport.jl#readme Arguably it could made be more prominent but since we haven't received any other questions I'm not sure if a more prominent explanation would be of general interest.

**Comment by ignace-computing** [comment]
Ok, no problem!
Thanks for the help.
